version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: turkceoabtdeyiz-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: turkceoabtdeyiz
    ports:
      - '5436:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
